# Generated by Django 5.2.18 on 2026-10-07 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0004_alter_product_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        help_text="Например 02/25 — печатается в паспорте и на бирках",
                        max_length=30,
                        verbose_name="Номер партии",
                    ),
                ),
                (
                    "invoice",
                    models.CharField(
                        blank=True,
                        help_text="Например TS2407202",
                        max_length=60,
                        verbose_name="Инвойс",
                    ),
                ),
                (
                    "factory_orders",
                    models.CharField(
                        blank=True,
                        help_text="Например Q571, Q595, Q604",
                        max_length=120,
                        verbose_name="Заказы завода",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("in_transit", "в пути"), ("received", "принята")],
                        default="in_transit",
                        max_length=12,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "received_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата приёмки"
                    ),
                ),
                (
                    "manufactured",
                    models.CharField(
                        blank=True,
                        help_text="Например 07.2025",
                        max_length=20,
                        verbose_name="Дата изготовления",
                    ),
                ),
                (
                    "passport_number",
                    models.CharField(
                        blank=True,
                        help_text="Например 09/002/25",
                        max_length=30,
                        verbose_name="Номер паспорта",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечание")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "партия",
                "verbose_name_plural": "партии",
                "ordering": ["-received_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Adjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("defect", "брак из Китая"),
                            ("shortage", "недостача"),
                            ("free_sample", "бесплатные образцы заказчику"),
                            ("inventory_minus", "инвентаризация: меньше"),
                            ("inventory_plus", "инвентаризация: больше"),
                        ],
                        max_length=20,
                        verbose_name="Причина",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("notes", models.TextField(blank=True, verbose_name="Комментарий")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.customer",
                        verbose_name="Заказчик (для образцов)",
                    ),
                ),
            ],
            options={
                "verbose_name": "списание / корректировка",
                "verbose_name_plural": "списания и корректировки",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdjustmentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.PositiveIntegerField(verbose_name="Кол-во, шт")),
                (
                    "adjustment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="stock.adjustment",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustment_lines",
                        to="catalog.product",
                        verbose_name="Изделие",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustment_lines",
                        to="stock.batch",
                        verbose_name="Партия",
                    ),
                ),
            ],
            options={
                "ordering": ["product__code"],
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата отгрузки")),
                (
                    "ttn_number",
                    models.CharField(blank=True, max_length=30, verbose_name="№ ТТН"),
                ),
                (
                    "ttn_scan",
                    models.FileField(
                        blank=True, upload_to="ttn/%Y/", verbose_name="Скан ТТН"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечание")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments",
                        to="catalog.customer",
                        verbose_name="Заказчик",
                    ),
                ),
            ],
            options={
                "verbose_name": "отгрузка",
                "verbose_name_plural": "отгрузки",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.PositiveIntegerField(verbose_name="Кол-во, шт")),
                (
                    "price_byn",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Цена без НДС, BYN",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipment_lines",
                        to="stock.batch",
                        verbose_name="Партия",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipment_lines",
                        to="catalog.product",
                        verbose_name="Изделие",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="stock.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ["product__code", "batch__received_date"],
            },
        ),
        migrations.CreateModel(
            name="ReceiptLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qty_expected",
                    models.PositiveIntegerField(verbose_name="По документам, шт"),
                ),
                (
                    "qty_received",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Принято, шт"
                    ),
                ),
                (
                    "price_cny",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        max_digits=16,
                        null=True,
                        verbose_name="Цена Китая, CNY",
                    ),
                ),
                (
                    "landed_price_byn",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Приходная цена, BYN/шт",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="stock.batch",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_lines",
                        to="catalog.product",
                        verbose_name="Изделие",
                    ),
                ),
            ],
            options={
                "ordering": ["product__code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch", "product"),
                        name="one_line_per_product_in_batch",
                    )
                ],
            },
        ),
    ]
