# Generated by Django 5.2.18 on 2026-10-09 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_options"),
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartonSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qty_per_carton",
                    models.PositiveIntegerField(verbose_name="Шт. в коробке"),
                ),
                (
                    "gross_kg",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        verbose_name="Брутто коробки, кг",
                    ),
                ),
                (
                    "net_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Нетто коробки, кг",
                    ),
                ),
                (
                    "cartons",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Коробок в партии"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Откуда данные"
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cartons",
                        to="stock.batch",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="carton_specs",
                        to="catalog.product",
                        verbose_name="Изделие",
                    ),
                ),
            ],
            options={
                "verbose_name": "коробка",
                "verbose_name_plural": "коробки",
                "ordering": ["product__code", "-cartons", "-qty_per_carton"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch", "product", "qty_per_carton"),
                        name="one_carton_size_per_product_in_batch",
                    )
                ],
            },
        ),
    ]
