# Generated by Django 5.2.18 on 2026-10-07 17:49

import catalog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Заказчик"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Полное наименование"
                    ),
                ),
            ],
            options={
                "verbose_name": "заказчик",
                "verbose_name_plural": "заказчики",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Код (по штампу чертежа)",
                    ),
                ),
                (
                    "code_key",
                    models.CharField(editable=False, max_length=100, unique=True),
                ),
                (
                    "yapib",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Обозначение ЯПИБ",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("straight", "прямой"),
                            ("angle", "угловой"),
                            ("reducer", "переход"),
                            ("angle_reducer", "угловой переход"),
                            ("corrugated", "гофрированный"),
                            ("hose", "рукав"),
                        ],
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("black", "чёрный"),
                            ("blue", "синий"),
                            ("red", "красный"),
                        ],
                        max_length=10,
                        verbose_name="Цвет",
                    ),
                ),
                (
                    "angle",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Угол, °"
                    ),
                ),
                (
                    "d1",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=6,
                        null=True,
                        verbose_name="Ø1, мм",
                    ),
                ),
                (
                    "d2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=6,
                        null=True,
                        verbose_name="Ø2, мм",
                    ),
                ),
                (
                    "l1",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=7,
                        null=True,
                        verbose_name="L1, мм",
                    ),
                ),
                (
                    "l2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=7,
                        null=True,
                        verbose_name="L2, мм",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("drawing_pending", "чертёж ожидается"),
                            ("sample", "образец"),
                            ("serial", "серия"),
                            ("archived", "снят"),
                        ],
                        default="sample",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечание")),
                ("search_text", models.TextField(blank=True, editable=False)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.customer",
                        verbose_name="Заказчик",
                    ),
                ),
            ],
            options={
                "verbose_name": "изделие",
                "verbose_name_plural": "изделия",
                "ordering": ["customer__name", "code"],
            },
        ),
        migrations.CreateModel(
            name="ProductAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="Написание")),
                (
                    "normalized",
                    models.CharField(editable=False, max_length=255, unique=True),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("invoice", "инвойс"),
                            ("packing_list", "упаковочный лист завода"),
                            ("carton", "маркировка коробки"),
                            ("ttn", "ТТН"),
                            ("request", "заявка заказчика"),
                            ("other", "другое"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Источник",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "синоним",
                "verbose_name_plural": "синонимы",
                "ordering": ["text"],
            },
        ),
        migrations.CreateModel(
            name="DrawingFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("pdf", "чертёж (PDF)"),
                            ("signed", "скан с подписями"),
                            ("china", "для китайского завода"),
                        ],
                        default="pdf",
                        max_length=10,
                        verbose_name="Вид",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=catalog.models.drawing_upload_to, verbose_name="Файл"
                    ),
                ),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drawing_files",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "файл чертежа",
                "verbose_name_plural": "файлы чертежей",
                "ordering": ["kind"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "kind"), name="one_drawing_file_per_kind"
                    )
                ],
            },
        ),
    ]
