# Generated by Django 5.2.18 on 2026-10-07 17:52

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawingfile",
            name="preview",
            field=models.ImageField(
                blank=True,
                editable=False,
                upload_to=catalog.models.drawing_upload_to,
                verbose_name="Картинка для просмотра",
            ),
        ),
    ]
