# Generated by Django 5.2.18 on 2026-10-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_drawingfile_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drawingfile",
            name="kind",
            field=models.CharField(
                choices=[
                    ("pdf", "чертёж (PDF)"),
                    ("signed", "скан с подписями"),
                    ("china", "чертёж китайского завода"),
                    ("customer", "чертёж заказчика"),
                ],
                default="pdf",
                max_length=10,
                verbose_name="Вид",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.CharField(
                max_length=100, verbose_name="Код (по штампу чертежа)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="code_key",
            field=models.CharField(db_index=True, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name="productalias",
            name="source",
            field=models.CharField(
                choices=[
                    ("invoice", "инвойс"),
                    ("packing_list", "упаковочный лист завода"),
                    ("carton", "маркировка коробки"),
                    ("ttn", "ТТН"),
                    ("request", "заявка заказчика"),
                    ("factory", "код китайского завода"),
                    ("customer", "обозначение заказчика"),
                    ("other", "другое"),
                ],
                default="other",
                max_length=20,
                verbose_name="Источник",
            ),
        ),
    ]
