# Generated by Django 5.2.18 on 2026-10-07 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_drawingfile_kind_alter_product_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["customer__name", "kind", "d1", "angle", "l1", "code"],
                "verbose_name": "изделие",
                "verbose_name_plural": "изделия",
            },
        ),
    ]
